### ISSUE TITLE
[openstack][pike] Compute[:openstack].servers doesn't work

### ISSUE THREAD

**Issue by aibondarenko** [fog/fog-openstack#362] opened 2018-02-06 15:02 UTC
Trying to connect locally deployed openstack (pike) with fog 1.42.0.

Firstly, curl connection works well with the command: https://hastebin.com/fihojuqize.scala

With this in mind, i've created fog credentials file: https://hastebin.com/hexanixucu.scala and run

fog openstack
Compute[:openstack].servers

This leads to an error like [full text here](https://hastebin.com/bucugizipi.php):

```
  :status        => 302
  :status_line   => "HTTP/1.1 302 Found\r\n"

    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/middlewares/expects.rb:7:in `response_call'
    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/connection.rb:414:in `response'
    from /var/lib/gems/2.3.0/gems/excon-0.60.0/lib/excon/connection.rb:263:in `request'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/connection.rb:81:in `request'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack.rb:610:in `get_version'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack.rb:583:in `get_supported_microversion'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack/core.rb:122:in `set_microversion'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/openstack/core.rb:212:in `authenticate'
    from /var/lib/gems/2.3.0/gems/fog-openstack-0.1.23/lib/fog/compute/openstack.rb:397:in `initialize'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/services_mixin.rb:16:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/compute.rb:54:in `new'
    from /var/lib/gems/2.3.0/gems/fog-core-1.45.0/lib/fog/core/services_mixin.rb:4:in `[]'
    from (irb):1:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/fog-1.42.0/bin/fog:76:in `block in <top (required)>'
    from /var/lib/gems/2.3.0/gems/fog-1.42.0/bin/fog:76:in `catch'
    from /var/lib/gems/2.3.0/gems/fog-1.42.0/bin/fog:76:in `<top (required)>'
    from /usr/local/bin/fog:23:in `load'
    from /usr/local/bin/fog:23:in `<main>
```
First request to "/identity/v3/auth/tokens" was complete, but overall result is bad..

Worth to be mentioned - i've cntlm proxy configured.

**Comment by voelzmo** [comment] 2018-02-06 15:26
Seems like your catalog returns this for the compute/nova endpoint
```
{\"endpoints\": [{\"url\": \"http://192.168.122.48/compute/v2.1\", \"interface\": \"public\", \"region\": \"RegionOne\", \"region_id\": \"RegionOne\", \"id\": \"f3fe9c96f518450fb68c132ee01fbec8\"}], \"type\": \"compute\", \"id\": \"aeacaae9742943fda07dc80a1ec7de20\", \"name\": \"nova\"}
```

And the implementation for fetching microversions ignores the path https://github.com/fog/fog-openstack/blob/a0dff17ba9a0054c665aa967a32be19506693269/lib/fog/openstack.rb#L609

Therefore, it makes a request to http://192.168.122.48, which fails, because it is not nova answering there, but a redirect to Horizon happens.

**Comment by aibondarenko** [comment] 2018-02-06 18:04
I'll try to add the path and than retest the case.
Actually, the root of my trouble was failed cf-openstack-validator,
i came down to manual fog operations just to investigate the trouble.

**Comment by aibondarenko** [comment] 2018-02-07 08:15
Ok, i've changed the way fog core connection created,
for now i get 200 OK for this step, but the next line i see
"Fog::Service::NotFound: openstack has no compute service"

It looks strange to me, since i try to create an instance via horizon - and it wotks.

**Comment by aibondarenko** [comment] 2018-02-07 14:51
it looks like by simple adding path to the request uri i've broke some tests..
guess i need some sophisticated condition..

**Comment by gildub** [comment] 2018-02-08 22:53
@aibondarenko, I wonder how your Identity service works, your authentication details look different than usual with no service port and 'identity` in the path, could you please detail:
```ruby
openstack_auth_url: "172.16.0.1:5000/v3/auth/tokens"
```
Also if there is an issue with compute, it should solved into the Compute class (or related) but I would not recommend patching the overall connection super class.

**Comment by aibondarenko** [comment] 2018-02-09 07:05
>  I wonder how your Identity service works, your authentication details look different than usual with no service port and identity in the path

I'm just using out-of-the-box devstack version "pike".

> could you please detail and provide your catalog output

As far as i understand, my catalog output already in the initial post,
but here is the beautified copy of it: https://hastebin.com/melosiyiyi.tex.

> Also if there is an issue with compute, it should solved into the Compute class (or related)

i'll see what can be done there..

**Comment by voelzmo** [comment] 2018-02-09 07:45
@gildub it seems to be a mixture of what the nova url looks like on a pike devstack (no distinction by port, but by path) and the way how the code is written to determine the microversion to use. See https://github.com/fog/fog-openstack/issues/362#issuecomment-363456987 where I tried to highlight the relevant parts.

**Comment by gildub** [comment] 2018-02-13 22:15
@aibondarenko, thanks for the catalog clarification, never mind as this isn't an issue.
@voelzmo, thanks for highlight.

I can definitely reproduce it against Pike, looking into it....

**Comment by aibondarenko** [comment] 2018-02-15 07:36
@gildub could you please provide some information on how you deploy your pike? was it done through devstack? Also, could you please provide your fog credentials file content?

**Comment by gildub** [comment] 2018-02-20 01:03
@aibondarenko, I used OSP11 (Red Hat OpenStack Platform) installed with TripleO along with the following credentials: 
```ruby  
auth = {
    openstack_auth_url: 'http://192.0.2.6:5000/v3/auth/tokens',
    openstack_username: 'admin',
    openstack_api_key: 'secret',
    openstack_project_name: 'admin',
    openstack_domain_id: 'default'
  }

```
I tried again with latest fog-openstack release 0.1.23, using patch https://github.com/fog/fog-openstack/pull/347 and I tried both fog-core 1.42.0 and 1.45.0.

**Comment by aibondarenko** [comment] 2018-02-20 15:23
AFAIK, there is no port number in current openstack installation (see also https://ask.openstack.org/en/question/110918/after-insalling-devstack-httpserver-ip5000-not-accessible/). I've tried ocata, pike and queens. 
Even if you're using some openstack deployment with the port in url - how one should handle the default one?
Is there a way to deploy it with custom url?

**Comment by gildub** [comment] 2018-07-12 10:17
@voelzmo, one of the great benefit of OpenLab is to be able to run test against different openstack and not just DevStack. Although I believe we need to address the way fog-openstack "assume" API version through the path.

**Comment by voelzmo** [comment] 2018-07-12 10:38
@gildub what I'm saying is: There is no such issue currently on a non-DevStack OpenStack, as everyone sets those up in the way fog-openstack assumes it to be. However, now that we have a way to easily spin up tests against DevStack in any version, and given that previously in this ticket reproducibility of the original error report seemed to be difficult: Can we reproduce this error right now? If so it should be possible to fix it, probably in the way you mentioned.

**Comment by gildub** [comment] 2018-07-12 11:59
@voelzmo, I think we're on the same page. I'll try to reproduce it against devstack and I'll like to get a more formal consumption of the endpoints although it'll more likely mean breaking from 0.1.x and go 0.2.x or even 1.x version.

**Comment by gildub** [comment] 2018-07-16 03:21
@aibondarenko, @voelzmo,

I can't reproduce it, at least with latest of both devstack (pre Rocky, commit 3b5477d6356a62d7d64a519a4b1ac99309d251c0) and fog-openstack (0.1.27).

I used following credentials:
```ruby
auth_url = 'http://192.168.1.7/identity/v3/auth/tokens'
username = 'admin'
password = 'password'
project  = 'admin'
domain   = 'default'
```

**Comment by gildub** [comment] 2018-07-17 07:04
@aibondarenko,

I confirm exactly what you've experienced, and I wish I investigated sooner!

There is effectively an issue with the URI path which basically break any endpoint using it, like most of the time in DevStack. This is going to be addressed with https://github.com/fog/fog-openstack/pull/408.

With above fix, the compute service Fog::Compute::OpenStack.new then returns "302 - found".

**Comment by gildub** [comment] 2018-07-18 04:41
The return code "302 - found" is actually because the root path "/" was missing in order to get the versions. This has been addressed in #408 as well.

The next error is currently due to a [devstack bug](https://bugs.launchpad.net/nova/+bug/1782284).
Once fixed the compute service will behave normally.

**Comment by gildub** [comment] 2018-07-25 02:45
Actually the issue with devstack is because nova (but kinda of the same for other services) endpoint is http://192.168.1.8/compute/v2.1 which obviously points directly to a version and therefore creates an issue as the list of versions is expected for the discovery. This is inherently happening because of the way fog-openstack handles api versions.

**Comment by gildub** [comment] 2018-08-02 04:10
A workaround would be to replace nova endpoint with '/compute' in order to be "version less" and allow version discovery to take place. 

Unfortunately that doesn't work because fog-openstack is looking for a version in the path. This is happening because of historical evolution with OpenStack introducing new versions.

The right way is to discover the versions available and match against the one is desired by the client if any otherwise assume the latest offered. Tampering with the URL is FORBIDDEN.

**Comment by TommyLike** [comment] 2018-08-13 02:45
This pull request #412 fixes the issue when 'version' rather than 'versions' is returned from the show version API, for example [nova](https://developer.openstack.org/api-ref/compute/#show-details-of-specific-api-version)

**Comment by gildub** [comment] 2018-08-15 13:40
@voelzmo, the refactor is here https://github.com/fog/fog-openstack/pull/413 ;)

**Comment by voelzmo** [comment] 2018-08-17 11:11
@gildub that's quite a PR, impressive!

**Comment by gildub** [comment] 2018-08-20 02:30
@voelzmo, thanks! Well it's bigger than I would like to but one thing leading to another from authentication versions, token, catalog, to endpoints are making the whole. I believe it helps with many issues including this one. Please help reviewing it, actually it's not too bad, lots of VCR files :)

**Comment by gildub** [comment] 2018-11-02 04:57
Now that the dust has settled with PR#413 I believe we can close this issue. Thanks everyone for help and support.

**Closed by gildub** 2018-11-02 04:57 UTC
